[workspace]
authors = ["lxbc135 <lxbc135@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pybind11-test"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pybind11 = ">=3.0.2,<4"
pip = ">=23.0,<24"
scikit-build-core = ">=0.12.1,<0.13"
